#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'
APP_ROOT = DAEMON_ROOT

begin
  require 'rubigen'
rescue LoadError
  require 'rubygems'
  require 'rubigen'
end
require 'rubigen/scripts/generate'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])
RubiGen::Base.use_component_sources! [:daemon]
RubiGen::Scripts::Generate.new.run(ARGV)
